apiVersion: apps/v1
kind: Deployment
metadata:
  name: smf-deployment
  labels:
    app: smf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smf
  template:
    metadata:
      labels:
        app: smf
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"192.168.2.4\"]"
    spec:
      containers:
        - name: smf
          image: steven30801/free5gc-build:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["-c", "/usr/src/free5gc-stage-1/free5gc-smfd"]
          stdin: true
          tty: true
          volumeMounts:
            - name: free5gc-config
              mountPath: /usr/src/free5gc-stage-1/install/etc/free5gc/free5gc.conf
              subPath: free5gc.conf
            - name: smf-freediameter-config
              mountPath: /usr/src/free5gc-stage-1/install/etc/free5gc/freeDiameter/smf.conf
              subPath: smf.conf
      volumes:
        - name: free5gc-config
          configMap: 
            name: free5gc-configmap
        - name: smf-freediameter-config
          configMap:
            name: smf-freediameter-configmap
