apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcrf-deployment
  labels:
    app: pcrf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcrf
  template:
    metadata:
      labels:
        app: pcrf
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"192.168.2.5\"]"
    spec:
      containers:
        - name: pcrf
          image: steven30801/free5gc-build:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["-c", "/usr/src/free5gc-stage-1/nextepc-pcrfd"]
          stdin: true
          tty: true
          volumeMounts:
            - name: free5gc-config
              mountPath: /usr/src/free5gc-stage-1/install/etc/free5gc/free5gc.conf
              subPath: free5gc.conf
            - name: pcrf-freediameter-config
              mountPath: /usr/src/free5gc-stage-1/install/etc/free5gc/freeDiameter/pcrf.conf
              subPath: pcrf.conf
          securityContext:
            privileged: true
      volumes:
        - name: free5gc-config
          configMap: 
            name: free5gc-configmap
        - name: pcrf-freediameter-config
          configMap:
            name: pcrf-freediameter-configmap
