apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf-deployment
  labels:
    app: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      labels:
        app: amf
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"192.168.2.2\"]"
    spec:
      containers:
        - name: amf
          image: steven30801/free5gc-build:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["-c", "/usr/src/free5gc-stage-1/free5gc-amfd"]
          stdin: true
          tty: true
          ports:
            - name: sctp
              containerPort: 36412
              protocol: SCTP
          volumeMounts:
            - name: free5gc-config
              mountPath: /usr/src/free5gc-stage-1/install/etc/free5gc/free5gc.conf
              subPath: free5gc.conf
            - name: amf-freediameter-config
              mountPath: /usr/src/free5gc-stage-1/install/etc/free5gc/freeDiameter/amf.conf
              subPath: amf.conf
      volumes:
        - name: free5gc-config
          configMap:
            name: free5gc-configmap
        - name: amf-freediameter-config
          configMap:
            name: amf-freediameter-configmap
