apiVersion: apps/v1
kind: Deployment
metadata:
  name: hss-deployment
  labels:
    app: hss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hss
  template:
    metadata:
      labels:
        app: hss
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"192.168.2.3\"]"
    spec:
      containers:
        - name: hss
          image: steven30801/free5gc-build:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["-c", "/usr/src/free5gc-stage-1/nextepc-hssd"]
          stdin: true
          tty: true
          volumeMounts:
            - name: free5gc-config
              mountPath: /usr/src/free5gc-stage-1/install/etc/free5gc/free5gc.conf
              subPath: free5gc.conf
            - name: hss-freediameter-config
              mountPath: /usr/src/free5gc-stage-1/install/etc/free5gc/freeDiameter/hss.conf
              subPath: hss.conf
      volumes:
        - name: free5gc-config
          configMap: 
            name: free5gc-configmap
        - name: hss-freediameter-config
          configMap:
            name: hss-freediameter-configmap
